# Generated by Django 4.2.15 on 2025-09-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=120)),
                ('anio', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
